### ISSUE TITLE
rustc minimal required version question

### ISSUE THREAD

**Issue by jspaaks** [passcod/citeworks#1]
Hello and thanks for making this tool! I was trying it out and got a message: 

```text
Caused by:
  package `citeworks-cli v0.1.0` cannot be built because it requires rustc 1.63.0 or
  newer, while the currently active rustc version is 1.59.0
```

I was wondering if it would be possible to lower the required version such that users who are installing Rust from their package managers can use it out of the box (I get rustc 1.59.0 from the Ubuntu repos). I guess it will depend on whether the program uses some recently introduced language/compiler features (I'm not really familiar with Rust myself so I wouldn't know).

Thanks!

**Comment by passcod** [comment]
I think I _did_ use 1.63 features, but I can get some pre-built releases going if that would help?

**Comment by passcod** [comment]
Here, these should work: https://github.com/passcod/citeworks/releases/tag/cli-0.1.0

**Comment by jspaaks** [comment]
Thanks I managed to get it working yesterday by git cloning and replacing the required version strings, then rebuilding. I just thought the tool would see more adoption if the threshold was a bit lower. Keep up the good work!
